[["C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/__init__.py",[false,[["__all__",true,13,null],["catch",true,2,["catch","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_catch.py",12]],["BaseExceptionGroup",true,2,["BaseExceptionGroup","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_exceptions.py",5]],["ExceptionGroup",true,2,["ExceptionGroup","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_exceptions.py",5]],["format_exception",true,2,["format_exception","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_formatting.py",12]],["format_exception_only",true,2,["format_exception_only","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_formatting.py",12]],["print_exc",true,2,["print_exc","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_formatting.py",12]],["print_exception",true,2,["print_exception","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_formatting.py",12]],["suppress",true,2,["suppress","C:/Users/82104/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/exceptiongroup/_suppress.py",5]]]]]]